// For this project development
import '@vue/runtime-core'
import { RockForm, RockFormItem, RockFormItemGi } from '../src/form'
import { RockIconify } from "../src/iconify";
import { RockLocalePicker } from "../src/localePicker";
import { RockTable } from "../src/table";
import { RockSpace } from "../src/space";
import { RockDropDown } from "../src/dropdown";
import { RockAvatar } from "../src/avatar";
import { RockThing } from "../src/thing";
import { RockBadge } from "../src/badge";
import { RockBreadcrumb, RockBreadcrumbItem } from "../src/breadcrumb";
import { RockButton, RockButtonGroup } from "../src/button";
import { RockCard } from "../src/card";
import { RockCheckbox, RockCheckboxGroup } from "../src/checkbox";
import { RockCol } from "../src/col";
import { RockConfig } from "../src/config";
import { RockDatePicker } from "../src/dataPicker";
import { RockDivider } from "../src/divider";
import { RockDrawer, RockDrawerContent } from "../src/drawer";
import { RockEllipsis } from "../src/ellipsis";
import { RockGrid, RockGridItem } from "../src/grid";
import { RockDynamicInput, RockInput, RockInputGroup, RockInputGroupLabel } from "../src/input";
import { RockInputNumber } from "../src/inputNumber";
import { RockLayout, RockLayoutContent, RockLayoutFooter, RockLayoutHeader, RockLayoutSider } from "../src/layout";
import { RockList, RockListItem } from "../src/list";
import { RockMenu } from "../src/menu";
import { RockModal } from "../src/modal";
import { RockPopover } from "../src/popover";
import { RockNotificationProvider } from "../src/prividerNotification";
import { RockDialogProvider } from "../src/providerDialog";
import { RockMessageProvider } from "../src/providerMessage";
import { RockResult } from "../src/result";
import { RockRow } from "../src/row";
import { RockScrollbar } from "../src/scrollbar";
import { RockPopSelect, RockSelect } from "../src/select";
import { RockSkeleton } from "../src/skeleton";
import { RockSpinner } from "../src/spinner";
import { RockSwitch } from "../src/switch";
import { RockTab, RockTabPane, RockTabs } from "../src/tabs";
import { RockDynamicTags, RockTag } from "../src/tag";
import { RockGradientText, RockText } from "../src/text";
import { RockTooltip } from "../src/tooltip";
import { RockTree } from "../src/tree";
import { RockTreeSelect } from "../src/treeSelect";
import { RockH1, RockH2, RockH3, RockH4, RockH5, RockH6 } from "../src/typography";
import { RockCubeTable } from "../src/cubeTable";
import { RockProgress } from "../src/progress";
import { RockPageHeader } from "../src/pageHeader";

export declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    WmqAvatar:typeof RockAvatar;
    WmqBadge:typeof RockBadge;
    WmqBreadcrumb:typeof RockBreadcrumb;
    WmqBreadcrumbItem:typeof RockBreadcrumbItem;
    WmqButton:typeof RockButton;
    WmqButtonGroup:typeof RockButtonGroup;
    WmqCard:typeof RockCard;
    WmqCheckbox:typeof RockCheckbox;
    WmqCheckboxGroup:typeof RockCheckboxGroup;
    WmqCol:typeof RockCol;
    WmqConfig:typeof RockConfig;
    WmqCubeTable:typeof RockCubeTable;
    WmqDatePicker:typeof RockDatePicker;
    WmqDivider:typeof RockDivider;
    WmqDrawer:typeof RockDrawer;
    WmqDrawerContent:typeof RockDrawerContent;
    WmqDropDown:typeof RockDropDown;
    WmqEllipsis:typeof RockEllipsis;
    WmqForm:typeof RockForm;
    WmqFormItem:typeof RockFormItem;
    WmqFormItemGi:typeof RockFormItemGi;
    WmqGrid:typeof RockGrid;
    WmqGridItem:typeof RockGridItem;
    WmqIconify:typeof RockIconify
    WmqInput:typeof RockInput;
    WmqInputNumber:typeof RockInputNumber;
    WmqDynamicInput:typeof RockDynamicInput;
    WmqInputGroup:typeof RockInputGroup;
    WmqInputGroupLabel:typeof RockInputGroupLabel;
    WmqLayout:typeof RockLayout;
    WmqLayoutContent:typeof RockLayoutContent;
    WmqLayoutHeader:typeof RockLayoutHeader;
    WmqLayoutFooter:typeof RockLayoutFooter;
    WmqLayoutSider:typeof RockLayoutSider;
    WmqList:typeof RockList;
    WmqListItem:typeof RockListItem;
    WmqLocalePicker:typeof RockLocalePicker;
    WmqMenu:typeof RockMenu;
    WmqModal:typeof RockModal;
    WmqPopover:typeof RockPopover;
    WmqNotificationProvider:typeof RockNotificationProvider;
    WmqDialogProvider:typeof RockDialogProvider;
    WmqMessageProvider:typeof RockMessageProvider;
    WmqResult:typeof RockResult;
    WmqRow:typeof RockRow;
    WmqScrollbar:typeof RockScrollbar;
    WmqSelect:typeof RockSelect;
    WmqPopSelect:typeof RockPopSelect;
    WmqSkeleton:typeof RockSkeleton;
    WmqSpace:typeof RockSpace;
    WmqSpinner:typeof RockSpinner;
    WmqSwitch:typeof RockSwitch;
    WmqTable:typeof RockTable;
    WmqTab:typeof RockTab;
    WmqTabPane:typeof RockTabPane;
    WmqTabs:typeof RockTabs;
    WmqTag:typeof RockTag;
    WmqDynamicTags:typeof RockDynamicTags;
    WmqText:typeof RockText;
    WmqGradientText:typeof RockGradientText;
    WmqThing:typeof RockThing;
    WmqTooltip:typeof RockTooltip;
    WmqTree:typeof RockTree;
    WmqTreeSelect:typeof RockTreeSelect;
    WmqProgress:typeof RockProgress;
    WmqPageHeader:typeof RockPageHeader;
    WmqH1:typeof RockH1;
    WmqH2:typeof RockH2;
    WmqH3:typeof RockH3;
    WmqH4:typeof RockH4;
    WmqH5:typeof RockH5;
    WmqH6:typeof RockH6;
  }
}
export {}

