# FROM reg.nexus.wmqhealth.com/tools/node-18.16.0-alpine-pnpm:latest
# FROM --platform=linux/amd64 node:16.20.2
FROM --platform=linux/amd64 node:18.18.2

LABEL CONTAINER.AUTHOR="Randy"
LABEL CONTAINER.AUTHOR.MAIL="zhangshi@tenez.com"

RUN npm install -g pnpm

# docker build -t localhub.aihelp.net/aihelp-tools/node-16.20.2-tools .