/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SwcButton {
        "bg": boolean;
        "circle": boolean;
        "disabled": boolean;
        "icon": string;
        "link": boolean;
        "loading": boolean;
        "loadingIcon": string;
        "plain": boolean;
        "round": boolean;
        "size": string;
        "suffixIcon": string;
        "text": boolean;
        "type": string;
    }
    interface SwcButtonGroup {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSwcButtonElement extends Components.SwcButton, HTMLStencilElement {
    }
    var HTMLSwcButtonElement: {
        prototype: HTMLSwcButtonElement;
        new (): HTMLSwcButtonElement;
    };
    interface HTMLSwcButtonGroupElement extends Components.SwcButtonGroup, HTMLStencilElement {
    }
    var HTMLSwcButtonGroupElement: {
        prototype: HTMLSwcButtonGroupElement;
        new (): HTMLSwcButtonGroupElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "swc-button": HTMLSwcButtonElement;
        "swc-button-group": HTMLSwcButtonGroupElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SwcButton {
        "bg"?: boolean;
        "circle"?: boolean;
        "disabled"?: boolean;
        "icon"?: string;
        "link"?: boolean;
        "loading"?: boolean;
        "loadingIcon"?: string;
        "plain"?: boolean;
        "round"?: boolean;
        "size"?: string;
        "suffixIcon"?: string;
        "text"?: boolean;
        "type"?: string;
    }
    interface SwcButtonGroup {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "swc-button": SwcButton;
        "swc-button-group": SwcButtonGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "swc-button": LocalJSX.SwcButton & JSXBase.HTMLAttributes<HTMLSwcButtonElement>;
            "swc-button-group": LocalJSX.SwcButtonGroup & JSXBase.HTMLAttributes<HTMLSwcButtonGroupElement>;
        }
    }
}
