import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.8.1',
  date: '2024-01-28T14:26:59.454Z',
};
export default meta;
